name: mockapi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  provider: 6.0.5
  flutter: 
    sdk: flutter
  flutter_animate: ^4.1.1+1
  responsive_builder: ^0.7.0
  flutter_screenutil: ^5.8.4
  flutter_staggered_grid_view: ^0.6.2
  flutter_animated_button: ^2.0.3
  animated_text_kit: ^4.2.2

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter



flutter: 
  uses-material-design: true

  assets:
    - assets/images/.
